apiVersion: v1
kind: Service
metadata:
  name: nestjs-api-gateway
  labels:
    app: nestjs-api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nestjs-api-gateway